export const ENTRY_DELETE_START = "ENTRY_DELETE_START";
export const ENTRY_DELETE_SUCCESS = "ENTRY_DELETE_SUCCESS";
export const ENTRY_DELETE_FAIL = "ENTRY_DELETE_FAIL";

export const ENTRY_FAVORITE_START = "ENTRY_FAVORITE_START";
export const ENTRY_FAVORITE_SUCCESS = "ENTRY_FAVORITE_SUCCESS";
export const ENTRY_FAVORITE_FAIL = "ENTRY_FAVORITE_FAIL";
